spring:
  application:
    name: pay-pulse-web-api
  datasource:
    url: jdbc:postgresql://localhost:5432/paypulse_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true
    clean-disabled: true
